# Generated by Django 3.2.5 on 2021-11-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('lessons_count', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('is_free', models.BooleanField(default=0)),
                ('is_profession', models.BooleanField(default=0)),
                ('is_certified', models.BooleanField(default=0)),
                ('info1', models.CharField(blank=True, max_length=300)),
                ('info1_text', models.TextField(blank=True)),
                ('info2', models.CharField(blank=True, max_length=300)),
                ('info2_text', models.TextField(blank=True)),
                ('info3', models.CharField(blank=True, max_length=300)),
                ('info3_text', models.TextField(blank=True)),
                ('info4', models.CharField(blank=True, max_length=300)),
                ('info4_text', models.TextField(blank=True)),
                ('course_type', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video_link', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('video_minutes', models.IntegerField(blank=True, default=0)),
                ('task', models.TextField(blank=True)),
                ('task_code', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseItemParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('video_link', models.CharField(blank=True, max_length=300)),
                ('description1', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('description3', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('course_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courseitem')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.coursecategory'),
        ),
    ]
