# Generated by Django 3.2.8 on 2021-11-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211105_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseitemparagraph',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
