# Generated by Django 3.2.8 on 2021-12-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211117_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteuserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='New course', max_length=300)),
                ('start_datetime', models.DateTimeField(blank=True)),
                ('stop_datetime', models.DateTimeField(blank=True)),
                ('position', models.IntegerField(blank=True, default=0)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteuser')),
            ],
        ),
    ]
