# Generated by Django 3.2.8 on 2021-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_siteusercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('mini_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('create_datetime', models.DateTimeField(blank=True)),
                ('views_count', models.DateTimeField(blank=True)),
            ],
        ),
    ]
