# Generated by Django 3.2.8 on 2021-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
