# Generated by Django 3.2.8 on 2021-12-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='logo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
